1:[2025-08-27 03:54:38] local.ERROR: SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it (Connection: mysql, SQL: select * from `sessions` where `id` = lZPtP0mtoTxAb4HGbVruBiIUU6uHu5WhRDXk7vB9 limit 1) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 2002): SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it (Connection: mysql, SQL: select * from `sessions` where `id` = lZPtP0mtoTxAb4HGbVruBiIUU6uHu5WhRDXk7vB9 limit 1) at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php:824)
129:[2025-08-27 04:48:10] local.ERROR: SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it (Connection: mysql, SQL: select exists (select 1 from information_schema.tables where table_schema = schema() and table_name = 'migrations' and table_type in ('BASE TABLE', 'SYSTEM VERSIONED')) as `exists`) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 2002): SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it (Connection: mysql, SQL: select exists (select 1 from information_schema.tables where table_schema = schema() and table_name = 'migrations' and table_type in ('BASE TABLE', 'SYSTEM VERSIONED')) as `exists`) at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php:824)
210:[2025-08-27 04:52:56] local.ERROR: SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it (Connection: mysql, SQL: select exists (select 1 from information_schema.tables where table_schema = schema() and table_name = 'migrations' and table_type in ('BASE TABLE', 'SYSTEM VERSIONED')) as `exists`) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 2002): SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it (Connection: mysql, SQL: select exists (select 1 from information_schema.tables where table_schema = schema() and table_name = 'migrations' and table_type in ('BASE TABLE', 'SYSTEM VERSIONED')) as `exists`) at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php:824)
291:[2025-08-27 05:35:38] local.ERROR: Class "App\Http\Controllers\Carbon" not found {"userId":100,"exception":"[object] (Error(code: 0): Class \"App\\Http\\Controllers\\Carbon\" not found at D:\\xampp\\htdocs\\sellvada\\app\\Http\\Controllers\\DashboardController.php:99)
310:#17 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
311:#18 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
352:[2025-08-27 05:54:07] local.ERROR: Target class [TeamListController] does not exist. {"userId":100,"exception":"[object] (Illuminate\\Contracts\\Container\\BindingResolutionException(code: 0): Target class [TeamListController] does not exist. at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php:1162)
371:#17 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
372:#18 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
433:#18 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
434:#19 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
475:[2025-08-27 07:00:41] local.ERROR: syntax error, unexpected token "public", expecting end of file (View: D:\xampp\htdocs\sellvada\resources\views\app.blade.php) {"userId":100,"exception":"[object] (Illuminate\\View\\ViewException(code: 0): syntax error, unexpected token \"public\", expecting end of file (View: D:\\xampp\\htdocs\\sellvada\\resources\\views\\app.blade.php) at D:\\xampp\\htdocs\\sellvada\\app\\Http\\Controllers\\CartController.php:7)
477:#0 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Engines\\PhpEngine.php(59): Illuminate\\View\\Engines\\CompilerEngine->handleViewException(Object(ParseError), 1)
502:#25 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
503:#26 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
544:[previous exception] [object] (ParseError(code: 0): syntax error, unexpected token \"public\", expecting end of file at D:\\xampp\\htdocs\\sellvada\\app\\Http\\Controllers\\CartController.php:7)
583:#37 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
584:#38 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
625:[2025-08-27 11:44:52] local.ERROR: Namespace declaration statement has to be the very first statement or after any declare call in the script {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Namespace declaration statement has to be the very first statement or after any declare call in the script at D:\\xampp\\htdocs\\sellvada\\app\\Http\\Controllers\\CheckoutController.php:4)
629:[2025-08-27 11:45:54] local.ERROR: Class "Controller" not found {"exception":"[object] (Error(code: 0): Class \"Controller\" not found at D:\\xampp\\htdocs\\sellvada\\app\\Http\\Controllers\\CheckoutController.php:8)
671:[2025-08-27 11:51:05] local.ERROR: Class "Controller" not found {"exception":"[object] (Error(code: 0): Class \"Controller\" not found at D:\\xampp\\htdocs\\sellvada\\app\\Http\\Controllers\\CheckoutController.php:8)
713:[2025-08-27 11:51:38] local.ERROR: Namespace declaration statement has to be the very first statement or after any declare call in the script {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Namespace declaration statement has to be the very first statement or after any declare call in the script at D:\\xampp\\htdocs\\sellvada\\app\\Http\\Controllers\\CheckoutController.php:4)
717:[2025-08-27 11:56:03] local.ERROR: Namespace declaration statement has to be the very first statement or after any declare call in the script {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Namespace declaration statement has to be the very first statement or after any declare call in the script at D:\\xampp\\htdocs\\sellvada\\app\\Http\\Middleware\\HandleInertiaRequests.php:4)
721:[2025-08-27 11:57:17] local.ERROR: Namespace declaration statement has to be the very first statement or after any declare call in the script {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Namespace declaration statement has to be the very first statement or after any declare call in the script at D:\\xampp\\htdocs\\sellvada\\app\\Http\\Middleware\\HandleInertiaRequests.php:4)
725:[2025-08-27 11:57:36] local.ERROR: Cannot declare class HandleInertiaRequests, because the name is already in use {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot declare class HandleInertiaRequests, because the name is already in use at D:\\xampp\\htdocs\\sellvada\\app\\Http\\Middleware\\HandleInertiaRequests.php:10)
729:[2025-08-27 12:45:40] local.ERROR: Unable to locate file in Vite manifest: resources/js/Pages/Team.jsx. (View: D:\xampp\htdocs\sellvada\resources\views\app.blade.php) {"userId":103,"exception":"[object] (Illuminate\\View\\ViewException(code: 0): Unable to locate file in Vite manifest: resources/js/Pages/Team.jsx. (View: D:\\xampp\\htdocs\\sellvada\\resources\\views\\app.blade.php) at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Vite.php:988)
758:#27 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
759:#28 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
833:#31 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
834:#32 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
875:[2025-08-28 04:22:59] local.ERROR: SQLSTATE[01000]: Warning: 1265 Data truncated for column 'income_type' at row 1 (Connection: mysql, SQL: insert into `sell` (`buyer_id`, `sponsor_id`, `income_to_user_id`, `leg`, `product`, `amount`, `income`, `income_type`, `level`, `order_no`, `status`, `details`, `type`, `created_at`, `updated_at`) values (100, ?, 100, ?, 1, 3000, 0, sale, 0, ORD-20250828042258-8576, PAID, {"price":3000,"qty":1,"discount":0,"tax":150,"shipping":49}, checkout, 2025-08-28 04:22:58, 2025-08-28 04:22:58)) {"userId":100,"exception":"[object] (Illuminate\\Database\\QueryException(code: 01000): SQLSTATE[01000]: Warning: 1265 Data truncated for column 'income_type' at row 1 (Connection: mysql, SQL: insert into `sell` (`buyer_id`, `sponsor_id`, `income_to_user_id`, `leg`, `product`, `amount`, `income`, `income_type`, `level`, `order_no`, `status`, `details`, `type`, `created_at`, `updated_at`) values (100, ?, 100, ?, 1, 3000, 0, sale, 0, ORD-20250828042258-8576, PAID, {\"price\":3000,\"qty\":1,\"discount\":0,\"tax\":150,\"shipping\":49}, checkout, 2025-08-28 04:22:58, 2025-08-28 04:22:58)) at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php:824)
902:#25 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
903:#26 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
973:#27 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
974:#28 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
1015:[2025-08-28 06:18:38] local.ERROR: App\Console\Commands\RunBinaryMatching::sponsorQualifiedBySelfPurchase(): Argument #1 ($sponsorId) must be of type int, null given, called in D:\xampp\htdocs\sellvada\app\Console\Commands\RunBinaryMatching.php on line 75 {"exception":"[object] (TypeError(code: 0): App\\Console\\Commands\\RunBinaryMatching::sponsorQualifiedBySelfPurchase(): Argument #1 ($sponsorId) must be of type int, null given, called in D:\\xampp\\htdocs\\sellvada\\app\\Console\\Commands\\RunBinaryMatching.php on line 75 at D:\\xampp\\htdocs\\sellvada\\app\\Console\\Commands\\RunBinaryMatching.php:189)
1034:[2025-08-28 06:41:30] local.ERROR: Unclosed '{' on line 57 {"exception":"[object] (ParseError(code: 0): Unclosed '{' on line 57 at D:\\xampp\\htdocs\\sellvada\\routes\\web.php:60)
1067:[2025-08-28 06:41:38] local.ERROR: Unclosed '{' on line 57 {"exception":"[object] (ParseError(code: 0): Unclosed '{' on line 57 at D:\\xampp\\htdocs\\sellvada\\routes\\web.php:60)
1100:[2025-08-28 07:46:24] local.ERROR: Unable to locate file in Vite manifest: resources/js/Pages/Payouts.jsx. (View: D:\xampp\htdocs\sellvada\resources\views\app.blade.php) {"userId":100,"exception":"[object] (Illuminate\\View\\ViewException(code: 0): Unable to locate file in Vite manifest: resources/js/Pages/Payouts.jsx. (View: D:\\xampp\\htdocs\\sellvada\\resources\\views\\app.blade.php) at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Vite.php:988)
1129:#27 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
1130:#28 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
1204:#31 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
1205:#32 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
1246:[2025-08-28 07:46:42] local.ERROR: Unable to locate file in Vite manifest: resources/js/Pages/Payouts.jsx. (View: D:\xampp\htdocs\sellvada\resources\views\app.blade.php) {"userId":100,"exception":"[object] (Illuminate\\View\\ViewException(code: 0): Unable to locate file in Vite manifest: resources/js/Pages/Payouts.jsx. (View: D:\\xampp\\htdocs\\sellvada\\resources\\views\\app.blade.php) at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Vite.php:988)
1275:#27 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
1276:#28 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
1350:#31 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
1351:#32 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
1392:[2025-08-28 10:38:48] local.ERROR: Cannot use App\Http\Controllers\CheckoutController as CheckoutController because the name is already in use {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot use App\\Http\\Controllers\\CheckoutController as CheckoutController because the name is already in use at D:\\xampp\\htdocs\\sellvada\\routes\\web.php:15)
1396:[2025-08-28 10:38:52] local.ERROR: Cannot use App\Http\Controllers\CheckoutController as CheckoutController because the name is already in use {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot use App\\Http\\Controllers\\CheckoutController as CheckoutController because the name is already in use at D:\\xampp\\htdocs\\sellvada\\routes\\web.php:15)
1400:[2025-08-28 11:23:07] local.ERROR: Target class [ShopController] does not exist. {"userId":100,"exception":"[object] (Illuminate\\Contracts\\Container\\BindingResolutionException(code: 0): Target class [ShopController] does not exist. at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php:1162)
1423:#21 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
1424:#22 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
1489:#22 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
1490:#23 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
1531:[2025-08-28 11:26:17] local.ERROR: Target class [ShopController] does not exist. {"userId":100,"exception":"[object] (Illuminate\\Contracts\\Container\\BindingResolutionException(code: 0): Target class [ShopController] does not exist. at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php:1162)
1554:#21 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
1555:#22 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
1620:#22 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
1621:#23 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
1662:[2025-08-28 17:14:18] local.ERROR: No application encryption key has been specified. {"exception":"[object] (Illuminate\\Encryption\\MissingAppKeyException(code: 0): No application encryption key has been specified. at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Encryption\\EncryptionServiceProvider.php:83)
1714:[2025-08-28 17:14:24] local.ERROR: No application encryption key has been specified. {"exception":"[object] (Illuminate\\Encryption\\MissingAppKeyException(code: 0): No application encryption key has been specified. at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Encryption\\EncryptionServiceProvider.php:83)
1739:[2025-08-29 06:41:39] local.ERROR: Cannot declare class App\Http\Controllers\BinarySummaryContrliier, because the name is already in use {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot declare class App\\Http\\Controllers\\BinarySummaryContrliier, because the name is already in use at D:\\xampp\\htdocs\\sellvada\\app\\Http\\Controllers\\BinarySummaryController.php:11)
1743:[2025-08-29 06:42:28] local.ERROR: Cannot declare class App\Http\Controllers\BinarySummary, because the name is already in use {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot declare class App\\Http\\Controllers\\BinarySummary, because the name is already in use at D:\\xampp\\htdocs\\sellvada\\app\\Http\\Controllers\\BinarySummaryController.php:11)
1747:[2025-08-29 07:24:22] local.ERROR: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'q.rank_no' in 'field list' (Connection: mysql, SQL: select `i`.`amount`, `i`.`due_month`, `i`.`paid_at`, `q`.`rank_no`, `q`.`months_total`, `q`.`months_paid`, `i`.`id` from `repurchase_salary_installments` as `i` inner join `repurchase_salary_qualifications` as `q` on `q`.`id` = `i`.`qualification_id` where `q`.`sponsor_id` = 100 and date(`i`.`due_month`) = 2025-08-01 limit 1) {"userId":100,"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'q.rank_no' in 'field list' (Connection: mysql, SQL: select `i`.`amount`, `i`.`due_month`, `i`.`paid_at`, `q`.`rank_no`, `q`.`months_total`, `q`.`months_paid`, `i`.`id` from `repurchase_salary_installments` as `i` inner join `repurchase_salary_qualifications` as `q` on `q`.`id` = `i`.`qualification_id` where `q`.`sponsor_id` = 100 and date(`i`.`due_month`) = 2025-08-01 limit 1) at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php:824)
1774:#25 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
1775:#26 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
1845:#27 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
1846:#28 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
1887:[2025-08-29 07:27:33] local.ERROR: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'q.rank_no' in 'field list' (Connection: mysql, SQL: select `i`.`amount`, `i`.`due_month`, `i`.`paid_at`, `q`.`rank_no`, `q`.`months_total`, `q`.`months_paid`, `i`.`id` from `repurchase_salary_installments` as `i` inner join `repurchase_salary_qualifications` as `q` on `q`.`id` = `i`.`qualification_id` where `q`.`sponsor_id` = 100 and date(`i`.`due_month`) = 2025-08-01 limit 1) {"userId":100,"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'q.rank_no' in 'field list' (Connection: mysql, SQL: select `i`.`amount`, `i`.`due_month`, `i`.`paid_at`, `q`.`rank_no`, `q`.`months_total`, `q`.`months_paid`, `i`.`id` from `repurchase_salary_installments` as `i` inner join `repurchase_salary_qualifications` as `q` on `q`.`id` = `i`.`qualification_id` where `q`.`sponsor_id` = 100 and date(`i`.`due_month`) = 2025-08-01 limit 1) at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php:824)
1914:#25 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
1915:#26 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
1985:#27 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
1986:#28 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2027:[2025-08-29 09:37:07] local.ERROR: Namespace declaration statement has to be the very first statement or after any declare call in the script {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Namespace declaration statement has to be the very first statement or after any declare call in the script at D:\\xampp\\htdocs\\sellvada\\app\\Http\\Controllers\\Admin\\WalletDepositAdminController.php:4)
2031:[2025-08-29 09:37:12] local.ERROR: Namespace declaration statement has to be the very first statement or after any declare call in the script {"userId":100,"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Namespace declaration statement has to be the very first statement or after any declare call in the script at D:\\xampp\\htdocs\\sellvada\\app\\Http\\Controllers\\Admin\\WalletDepositAdminController.php:4)
2035:[2025-08-29 09:38:12] local.ERROR: Namespace declaration statement has to be the very first statement or after any declare call in the script {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Namespace declaration statement has to be the very first statement or after any declare call in the script at D:\\xampp\\htdocs\\sellvada\\app\\Http\\Controllers\\Admin\\WalletDepositAdminController.php:4)
2039:[2025-08-29 09:43:12] local.ERROR: Namespace declaration statement has to be the very first statement or after any declare call in the script {"userId":100,"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Namespace declaration statement has to be the very first statement or after any declare call in the script at D:\\xampp\\htdocs\\sellvada\\app\\Http\\Controllers\\Admin\\WalletDepositAdminController.php:4)
2043:[2025-08-29 13:10:04] local.ERROR: Command "make:create_address_table" is not defined.
2128:[2025-08-29 13:26:09] local.ERROR: Namespace declaration statement has to be the very first statement or after any declare call in the script {"userId":100,"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Namespace declaration statement has to be the very first statement or after any declare call in the script at D:\\xampp\\htdocs\\sellvada\\app\\Http\\Controllers\\Admin\\WalletDepositAdminController.php:4)
2132:[2025-08-29 13:26:57] local.ERROR: Cannot declare class WalletDepositAdminController, because the name is already in use {"userId":100,"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot declare class WalletDepositAdminController, because the name is already in use at D:\\xampp\\htdocs\\sellvada\\app\\Http\\Controllers\\Admin\\WalletDepositAdminController.php:9)
2136:[2025-08-29 13:27:00] local.ERROR: Cannot declare class WalletDepositAdminController, because the name is already in use {"userId":100,"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot declare class WalletDepositAdminController, because the name is already in use at D:\\xampp\\htdocs\\sellvada\\app\\Http\\Controllers\\Admin\\WalletDepositAdminController.php:9)
2140:[2025-08-29 14:19:10] local.ERROR: Cannot use App\Http\Controllers\CartController as CartController because the name is already in use {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot use App\\Http\\Controllers\\CartController as CartController because the name is already in use at D:\\xampp\\htdocs\\sellvada\\routes\\web.php:250)
2144:[2025-08-29 14:20:44] local.ERROR: Cannot use App\Http\Controllers\CartController as CartController because the name is already in use {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot use App\\Http\\Controllers\\CartController as CartController because the name is already in use at D:\\xampp\\htdocs\\sellvada\\routes\\web.php:250)
2148:[2025-08-30 14:11:45] local.ERROR: SQLSTATE[42000]: Syntax error or access violation: 1055 'u.position' isn't in GROUP BY (Connection: mysql, SQL: 
2168:        ) {"userId":11002,"exception":"[object] (Illuminate\\Database\\QueryException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1055 'u.position' isn't in GROUP BY (Connection: mysql, SQL: 
2232:#22 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2233:#23 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2274:[previous exception] [object] (PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1055 'u.position' isn't in GROUP BY at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php:406)
2300:#24 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2301:#25 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2342:[2025-08-30 14:15:22] local.ERROR: SQLSTATE[42000]: Syntax error or access violation: 1055 'laravel_sellvada.s.type' isn't in GROUP BY (Connection: mysql, SQL: 
2364:        ) {"userId":11002,"exception":"[object] (Illuminate\\Database\\QueryException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1055 'laravel_sellvada.s.type' isn't in GROUP BY (Connection: mysql, SQL: 
2432:#22 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2433:#23 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2474:[previous exception] [object] (PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1055 'laravel_sellvada.s.type' isn't in GROUP BY at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php:406)
2500:#24 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2501:#25 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2542:[2025-08-30 14:22:55] local.ERROR: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`laravel_sellvada`.`address`, CONSTRAINT `address_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users1` (`id`) ON DELETE CASCADE) (Connection: mysql, SQL: insert into `address` (`name`, `phone`, `line1`, `line2`, `city`, `state`, `pincode`, `country`, `is_default`, `user_id`, `updated_at`, `created_at`) values (Yogesh Kumar, 07357685240, ramsinghpur, ?, sri ganganager, Rajasthan, 335703, India, 0, 11005, 2025-08-30 14:22:55, 2025-08-30 14:22:55)) {"userId":11005,"exception":"[object] (Illuminate\\Database\\QueryException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`laravel_sellvada`.`address`, CONSTRAINT `address_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users1` (`id`) ON DELETE CASCADE) (Connection: mysql, SQL: insert into `address` (`name`, `phone`, `line1`, `line2`, `city`, `state`, `pincode`, `country`, `is_default`, `user_id`, `updated_at`, `created_at`) values (Yogesh Kumar, 07357685240, ramsinghpur, ?, sri ganganager, Rajasthan, 335703, India, 0, 11005, 2025-08-30 14:22:55, 2025-08-30 14:22:55)) at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php:824)
2576:#32 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2577:#33 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2654:#34 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2655:#35 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2696:[2025-08-30 14:27:12] local.ERROR: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`laravel_sellvada`.`address`, CONSTRAINT `address_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users1` (`id`) ON DELETE CASCADE) (Connection: mysql, SQL: insert into `address` (`name`, `phone`, `line1`, `line2`, `city`, `state`, `pincode`, `country`, `is_default`, `user_id`, `updated_at`, `created_at`) values (Yogesh Kumar, 07357685240, ramsinghpur, s, sri ganganager, Rajasthan, 335703, India, 1, 11005, 2025-08-30 14:27:12, 2025-08-30 14:27:12)) {"userId":11005,"exception":"[object] (Illuminate\\Database\\QueryException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`laravel_sellvada`.`address`, CONSTRAINT `address_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users1` (`id`) ON DELETE CASCADE) (Connection: mysql, SQL: insert into `address` (`name`, `phone`, `line1`, `line2`, `city`, `state`, `pincode`, `country`, `is_default`, `user_id`, `updated_at`, `created_at`) values (Yogesh Kumar, 07357685240, ramsinghpur, s, sri ganganager, Rajasthan, 335703, India, 1, 11005, 2025-08-30 14:27:12, 2025-08-30 14:27:12)) at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php:824)
2730:#32 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2731:#33 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2808:#34 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2809:#35 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2850:[2025-09-01 06:15:44] local.ERROR: syntax error, unexpected identifier "p" {"exception":"[object] (ParseError(code: 0): syntax error, unexpected identifier \"p\" at D:\\xampp\\htdocs\\sellvada\\routes\\web.php:147)
2883:[2025-09-01 06:41:11] local.ERROR: Class "User" not found {"userId":11003,"exception":"[object] (Error(code: 0): Class \"User\" not found at D:\\xampp\\htdocs\\sellvada\\routes\\web.php:145)
2898:#13 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2899:#14 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2940:[2025-09-01 07:37:30] local.ERROR: Unclosed '{' on line 144 does not match ')' {"exception":"[object] (ParseError(code: 0): Unclosed '{' on line 144 does not match ')' at D:\\xampp\\htdocs\\sellvada\\routes\\web.php:232)
2973:[2025-09-01 08:11:42] local.ERROR: syntax error, unexpected token "private", expecting end of file {"exception":"[object] (ParseError(code: 0): syntax error, unexpected token \"private\", expecting end of file at D:\\xampp\\htdocs\\sellvada\\app\\Console\\Commands\\RunBinaryMatching.php:231)
2985:[2025-09-01 12:14:13] local.ERROR: Call to undefined method App\Http\Controllers\TeamTreeController::index() {"userId":11020,"exception":"[object] (Error(code: 0): Call to undefined method App\\Http\\Controllers\\TeamTreeController::index() at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php:46)
3001:#14 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
3002:#15 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
3043:[2025-09-01 12:14:20] local.ERROR: Call to undefined method App\Http\Controllers\TeamTreeController::index() {"userId":11020,"exception":"[object] (Error(code: 0): Call to undefined method App\\Http\\Controllers\\TeamTreeController::index() at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php:46)
3059:#14 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
3060:#15 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
3101:[2025-09-01 12:51:12] local.ERROR: Call to undefined method App\Http\Controllers\TeamTreeController::show() {"userId":11020,"exception":"[object] (Error(code: 0): Call to undefined method App\\Http\\Controllers\\TeamTreeController::show() at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php:46)
3119:#16 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
3120:#17 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
3161:[2025-09-01 13:09:33] local.ERROR: Call to undefined method App\Http\Controllers\TeamTreeController::show() {"userId":11020,"exception":"[object] (Error(code: 0): Call to undefined method App\\Http\\Controllers\\TeamTreeController::show() at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php:46)
3177:#14 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
3178:#15 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
3219:[2025-09-01 13:09:35] local.ERROR: Call to undefined method App\Http\Controllers\TeamTreeController::show() {"userId":11020,"exception":"[object] (Error(code: 0): Call to undefined method App\\Http\\Controllers\\TeamTreeController::show() at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php:46)
3235:#14 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
3236:#15 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
3277:[2025-09-01 14:52:30] local.ERROR: Call to undefined method App\Http\Controllers\TeamTreeController::tree() {"userId":11025,"exception":"[object] (Error(code: 0): Call to undefined method App\\Http\\Controllers\\TeamTreeController::tree() at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php:46)
3291:#12 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
3292:#13 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
3333:[2025-09-01 14:53:30] local.ERROR: Call to undefined method App\Http\Controllers\TeamTreeController::tree() {"userId":11025,"exception":"[object] (Error(code: 0): Call to undefined method App\\Http\\Controllers\\TeamTreeController::tree() at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php:46)
3347:#12 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
3348:#13 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
3389:[2025-09-01 16:00:57] local.ERROR: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'laravel_sellvada.binary_tree' doesn't exist (Connection: mysql, SQL: 
3455:#22 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
3456:#23 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
3523:#24 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
3524:#25 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
3565:[2025-09-01 16:02:33] local.ERROR: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'laravel_sellvada.binary_tree' doesn't exist (Connection: mysql, SQL: 
3631:#22 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
3632:#23 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
3699:#24 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
3700:#25 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
3741:[2025-09-01 16:02:44] local.ERROR: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'laravel_sellvada.binary_tree' doesn't exist (Connection: mysql, SQL: 
3807:#22 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
3808:#23 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
3875:#24 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
3876:#25 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
3917:[2025-09-01 16:03:19] local.ERROR: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'u.left_child_id' in 'field list' (Connection: mysql, SQL: 
4049:#22 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
4050:#23 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
4117:#24 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
4118:#25 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
4159:[2025-09-01 16:29:59] local.ERROR: Unclosed '{' on line 12 (View: D:\xampp\htdocs\sellvada\resources\views\app.blade.php) {"userId":10999,"exception":"[object] (Illuminate\\View\\ViewException(code: 0): Unclosed '{' on line 12 (View: D:\\xampp\\htdocs\\sellvada\\resources\\views\\app.blade.php) at D:\\xampp\\htdocs\\sellvada\\app\\Http\\Controllers\\TeamTreeController.php:66)
4161:#0 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Engines\\PhpEngine.php(59): Illuminate\\View\\Engines\\CompilerEngine->handleViewException(Object(ParseError), 1)
4188:#27 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
4189:#28 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
4230:[previous exception] [object] (ParseError(code: 0): Unclosed '{' on line 12 at D:\\xampp\\htdocs\\sellvada\\app\\Http\\Controllers\\TeamTreeController.php:66)
4271:#39 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
4272:#40 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
4313:[2025-09-02 18:04:03] local.ERROR: Call to undefined method App\Http\Controllers\RepurchaseController::index() {"userId":10999,"exception":"[object] (Error(code: 0): Call to undefined method App\\Http\\Controllers\\RepurchaseController::index() at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php:46)
4331:#16 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
4332:#17 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
4373:[2025-09-03 06:56:49] local.ERROR: Call to undefined method App\Http\Controllers\RepurchaseController::show() {"userId":10999,"exception":"[object] (Error(code: 0): Call to undefined method App\\Http\\Controllers\\RepurchaseController::show() at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php:46)
4391:#16 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
4392:#17 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
4433:[2025-09-03 06:57:01] local.ERROR: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'laravel_sellvada.addresses' doesn't exist (Connection: mysql, SQL: select exists(select * from `addresses` where `user_id` = 10999) as `exists`) {"userId":10999,"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'laravel_sellvada.addresses' doesn't exist (Connection: mysql, SQL: select exists(select * from `addresses` where `user_id` = 10999) as `exists`) at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php:824)
4456:#21 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
4457:#22 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
4523:#23 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
4524:#24 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
4565:[2025-09-03 07:03:59] local.ERROR: Call to undefined method App\Http\Controllers\RepurchaseController::show() {"userId":10999,"exception":"[object] (Error(code: 0): Call to undefined method App\\Http\\Controllers\\RepurchaseController::show() at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php:46)
4583:#16 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
4584:#17 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
4625:[2025-09-03 07:04:54] local.ERROR: Call to undefined method App\Http\Controllers\RepurchaseController::show() {"userId":10999,"exception":"[object] (Error(code: 0): Call to undefined method App\\Http\\Controllers\\RepurchaseController::show() at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php:46)
4643:#16 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
4644:#17 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
4685:[2025-09-03 07:06:52] local.ERROR: Call to undefined method App\Http\Controllers\RepurchaseController::index() {"userId":10999,"exception":"[object] (Error(code: 0): Call to undefined method App\\Http\\Controllers\\RepurchaseController::index() at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php:46)
4699:#12 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
4700:#13 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
4741:[2025-09-03 07:08:56] local.ERROR: Call to undefined method App\Http\Controllers\RepurchaseController::index() {"userId":10999,"exception":"[object] (Error(code: 0): Call to undefined method App\\Http\\Controllers\\RepurchaseController::index() at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php:46)
4755:#12 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
4756:#13 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
4797:[2025-09-03 07:16:01] local.ERROR: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'laravel_sellvada.addresses' doesn't exist (Connection: mysql, SQL: select * from `addresses` where `user_id` = 10999 limit 1) {"userId":10999,"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'laravel_sellvada.addresses' doesn't exist (Connection: mysql, SQL: select * from `addresses` where `user_id` = 10999 limit 1) at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php:824)
4820:#21 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
4821:#22 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
4887:#23 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
4888:#24 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
4929:[2025-09-03 07:16:11] local.ERROR: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'laravel_sellvada.addresses' doesn't exist (Connection: mysql, SQL: select * from `addresses` where `user_id` = 10999 limit 1) {"userId":10999,"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'laravel_sellvada.addresses' doesn't exist (Connection: mysql, SQL: select * from `addresses` where `user_id` = 10999 limit 1) at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php:824)
4952:#21 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
4953:#22 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
5019:#23 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
5020:#24 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
5061:[2025-09-03 07:16:53] local.ERROR: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'laravel_sellvada.addresses' doesn't exist (Connection: mysql, SQL: select * from `addresses` where `user_id` = 10999 limit 1) {"userId":10999,"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'laravel_sellvada.addresses' doesn't exist (Connection: mysql, SQL: select * from `addresses` where `user_id` = 10999 limit 1) at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php:824)
5084:#21 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
5085:#22 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
5151:#23 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
5152:#24 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
5193:[2025-09-03 07:17:49] local.ERROR: Call to undefined method App\Http\Controllers\RepurchaseController::show() {"userId":10999,"exception":"[object] (Error(code: 0): Call to undefined method App\\Http\\Controllers\\RepurchaseController::show() at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php:46)
5211:#16 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
5212:#17 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
5253:[2025-09-03 07:19:11] local.ERROR: Call to undefined method App\Http\Controllers\RepurchaseController::show() {"userId":10999,"exception":"[object] (Error(code: 0): Call to undefined method App\\Http\\Controllers\\RepurchaseController::show() at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php:46)
5271:#16 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
5272:#17 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
5313:[2025-09-03 07:19:42] local.ERROR: Call to undefined method App\Http\Controllers\RepurchaseController::show() {"userId":10999,"exception":"[object] (Error(code: 0): Call to undefined method App\\Http\\Controllers\\RepurchaseController::show() at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php:46)
5331:#16 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
5332:#17 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
5373:[2025-09-03 07:19:58] local.ERROR: Call to undefined method App\Http\Controllers\RepurchaseController::index() {"userId":10999,"exception":"[object] (Error(code: 0): Call to undefined method App\\Http\\Controllers\\RepurchaseController::index() at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php:46)
5391:#16 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
5392:#17 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
5433:[2025-09-03 07:20:08] local.ERROR: Call to undefined method App\Http\Controllers\RepurchaseController::index() {"userId":10999,"exception":"[object] (Error(code: 0): Call to undefined method App\\Http\\Controllers\\RepurchaseController::index() at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php:46)
5451:#16 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
5452:#17 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
5493:[2025-09-03 07:20:21] local.ERROR: Call to undefined method App\Http\Controllers\RepurchaseController::index() {"userId":10999,"exception":"[object] (Error(code: 0): Call to undefined method App\\Http\\Controllers\\RepurchaseController::index() at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php:46)
5511:#16 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
5512:#17 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
5553:[2025-09-03 07:20:29] local.ERROR: Call to undefined method App\Http\Controllers\RepurchaseController::index() {"userId":10999,"exception":"[object] (Error(code: 0): Call to undefined method App\\Http\\Controllers\\RepurchaseController::index() at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php:46)
5571:#16 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
5572:#17 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
5613:[2025-09-03 07:34:26] local.ERROR: Call to undefined method App\Http\Controllers\RepurchaseController::index() {"userId":10999,"exception":"[object] (Error(code: 0): Call to undefined method App\\Http\\Controllers\\RepurchaseController::index() at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php:46)
5631:#16 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
5632:#17 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
5673:[2025-09-03 07:36:59] local.ERROR: Call to undefined method App\Http\Controllers\RepurchaseController::index() {"userId":10999,"exception":"[object] (Error(code: 0): Call to undefined method App\\Http\\Controllers\\RepurchaseController::index() at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php:46)
5691:#16 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
5692:#17 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
5733:[2025-09-03 07:40:18] local.ERROR: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'laravel_sellvada.addresses' doesn't exist (Connection: mysql, SQL: select * from `addresses` where `user_id` = 10999 limit 1) {"userId":10999,"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'laravel_sellvada.addresses' doesn't exist (Connection: mysql, SQL: select * from `addresses` where `user_id` = 10999 limit 1) at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php:824)
5760:#25 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
5761:#26 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
5831:#27 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
5832:#28 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
5873:[2025-09-03 07:40:53] local.ERROR: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'laravel_sellvada.addresses' doesn't exist (Connection: mysql, SQL: select * from `addresses` where `user_id` = 10999 limit 1) {"userId":10999,"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'laravel_sellvada.addresses' doesn't exist (Connection: mysql, SQL: select * from `addresses` where `user_id` = 10999 limit 1) at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php:824)
5900:#25 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
5901:#26 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
5971:#27 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
5972:#28 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
6013:[2025-09-03 07:49:58] local.ERROR: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'laravel_sellvada.addresses' doesn't exist (Connection: mysql, SQL: select * from `addresses` where `user_id` = 10999 limit 1) {"userId":10999,"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'laravel_sellvada.addresses' doesn't exist (Connection: mysql, SQL: select * from `addresses` where `user_id` = 10999 limit 1) at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php:824)
6040:#25 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
6041:#26 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
6111:#27 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
6112:#28 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
6153:[2025-09-03 08:47:08] local.ERROR: Repurchase Checkout Error: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'to_user_id' cannot be null (Connection: mysql, SQL: insert into `_payout` (`user_id`, `to_user_id`, `from_user_id`, `amount`, `status`, `method`, `type`, `created_at`, `updated_at`) values (10999, ?, 10999, 1000.00, paid, wallet, repurchase_payment, 2025-09-03 08:47:08, 2025-09-03 08:47:08)) {"trace":"#0 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(778): Illuminate\\Database\\Connection->runQueryCallback('insert into `_p...', Array, Object(Closure))
6174:#21 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
6175:#22 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
6215:[2025-09-03 08:47:17] local.ERROR: Repurchase Checkout Error: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'to_user_id' cannot be null (Connection: mysql, SQL: insert into `_payout` (`user_id`, `to_user_id`, `from_user_id`, `amount`, `status`, `method`, `type`, `created_at`, `updated_at`) values (10999, ?, 10999, 1000.00, paid, wallet, repurchase_payment, 2025-09-03 08:47:17, 2025-09-03 08:47:17)) {"trace":"#0 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(778): Illuminate\\Database\\Connection->runQueryCallback('insert into `_p...', Array, Object(Closure))
6236:#21 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
6237:#22 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
6277:[2025-09-03 08:48:29] local.ERROR: Repurchase Checkout Error: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'to_user_id' cannot be null (Connection: mysql, SQL: insert into `_payout` (`user_id`, `to_user_id`, `from_user_id`, `amount`, `status`, `method`, `type`, `created_at`, `updated_at`) values (10999, ?, 10999, 1000.00, paid, wallet, repurchase_payment, 2025-09-03 08:48:29, 2025-09-03 08:48:29)) {"trace":"#0 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(778): Illuminate\\Database\\Connection->runQueryCallback('insert into `_p...', Array, Object(Closure))
6298:#21 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
6299:#22 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
6339:[2025-09-03 08:48:53] local.ERROR: Repurchase Checkout Error: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'to_user_id' cannot be null (Connection: mysql, SQL: insert into `_payout` (`user_id`, `to_user_id`, `from_user_id`, `amount`, `status`, `method`, `type`, `created_at`, `updated_at`) values (10999, ?, 10999, 1000.00, paid, wallet, repurchase_payment, 2025-09-03 08:48:53, 2025-09-03 08:48:53)) {"trace":"#0 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(778): Illuminate\\Database\\Connection->runQueryCallback('insert into `_p...', Array, Object(Closure))
6360:#21 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
6361:#22 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
6401:[2025-09-03 08:49:21] local.ERROR: Repurchase Checkout Error: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'to_user_id' cannot be null (Connection: mysql, SQL: insert into `_payout` (`user_id`, `to_user_id`, `from_user_id`, `amount`, `status`, `method`, `type`, `created_at`, `updated_at`) values (10999, ?, 10999, 1000.00, paid, wallet, repurchase_payment, 2025-09-03 08:49:21, 2025-09-03 08:49:21)) {"trace":"#0 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(778): Illuminate\\Database\\Connection->runQueryCallback('insert into `_p...', Array, Object(Closure))
6422:#21 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
6423:#22 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
6463:[2025-09-03 09:10:31] local.ERROR: Repurchase Checkout Error: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'to_user_id' cannot be null (Connection: mysql, SQL: insert into `_payout` (`user_id`, `to_user_id`, `from_user_id`, `amount`, `status`, `method`, `type`, `created_at`, `updated_at`) values (10999, ?, 10999, 1000.00, paid, wallet, repurchase_payment, 2025-09-03 09:10:31, 2025-09-03 09:10:31)) {"trace":"#0 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(778): Illuminate\\Database\\Connection->runQueryCallback('insert into `_p...', Array, Object(Closure))
6484:#21 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
6485:#22 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
6525:[2025-09-03 09:10:49] local.ERROR: Repurchase Checkout Error: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'to_user_id' cannot be null (Connection: mysql, SQL: insert into `_payout` (`user_id`, `to_user_id`, `from_user_id`, `amount`, `status`, `method`, `type`, `created_at`, `updated_at`) values (10999, ?, 10999, 1000.00, paid, wallet, repurchase_payment, 2025-09-03 09:10:49, 2025-09-03 09:10:49)) {"trace":"#0 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(778): Illuminate\\Database\\Connection->runQueryCallback('insert into `_p...', Array, Object(Closure))
6546:#21 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
6547:#22 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
6587:[2025-09-03 09:10:52] local.ERROR: Repurchase Checkout Error: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'to_user_id' cannot be null (Connection: mysql, SQL: insert into `_payout` (`user_id`, `to_user_id`, `from_user_id`, `amount`, `status`, `method`, `type`, `created_at`, `updated_at`) values (10999, ?, 10999, 1000.00, paid, wallet, repurchase_payment, 2025-09-03 09:10:52, 2025-09-03 09:10:52)) {"trace":"#0 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(778): Illuminate\\Database\\Connection->runQueryCallback('insert into `_p...', Array, Object(Closure))
6608:#21 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
6609:#22 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
6649:[2025-09-03 09:14:03] local.ERROR: Repurchase Checkout Error: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'to_user_id' cannot be null (Connection: mysql, SQL: insert into `_payout` (`user_id`, `to_user_id`, `from_user_id`, `amount`, `status`, `method`, `type`, `created_at`, `updated_at`) values (10999, ?, 10999, 1000.00, paid, wallet, repurchase_payment, 2025-09-03 09:14:03, 2025-09-03 09:14:03)) {"trace":"#0 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(778): Illuminate\\Database\\Connection->runQueryCallback('insert into `_p...', Array, Object(Closure))
6670:#21 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
6671:#22 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
6711:[2025-09-03 09:18:10] local.ERROR: Repurchase Checkout Error: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'to_user_id' cannot be null (Connection: mysql, SQL: insert into `_payout` (`user_id`, `to_user_id`, `from_user_id`, `amount`, `status`, `method`, `type`, `created_at`, `updated_at`) values (10999, ?, 10999, 1000.00, paid, wallet, repurchase_payment, 2025-09-03 09:18:10, 2025-09-03 09:18:10))  
6712:[2025-09-03 09:23:43] local.ERROR: Repurchase Checkout Error: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'to_user_id' cannot be null (Connection: mysql, SQL: insert into `_payout` (`user_id`, `to_user_id`, `from_user_id`, `amount`, `status`, `method`, `type`, `created_at`, `updated_at`) values (10999, ?, 10999, 1000.00, paid, wallet, repurchase_payment, 2025-09-03 09:23:43, 2025-09-03 09:23:43))  
6713:[2025-09-03 09:30:05] local.ERROR: Repurchase Checkout Error: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'to_user_id' cannot be null (Connection: mysql, SQL: insert into `_payout` (`user_id`, `to_user_id`, `from_user_id`, `amount`, `status`, `method`, `type`, `created_at`, `updated_at`) values (10999, ?, 10999, 1000.00, paid, wallet, repurchase_payment, 2025-09-03 09:30:05, 2025-09-03 09:30:05))  
6714:[2025-09-03 09:47:44] local.ERROR: Repurchase Checkout Error: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'to_user_id' cannot be null (Connection: mysql, SQL: insert into `_payout` (`user_id`, `to_user_id`, `from_user_id`, `amount`, `status`, `method`, `type`, `created_at`, `updated_at`) values (10999, ?, 10999, 1000, paid, wallet, repurchase_payment, 2025-09-03 09:47:44, 2025-09-03 09:47:44))  
6715:[2025-09-03 09:47:54] local.ERROR: Repurchase Checkout Error: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'to_user_id' cannot be null (Connection: mysql, SQL: insert into `_payout` (`user_id`, `to_user_id`, `from_user_id`, `amount`, `status`, `method`, `type`, `created_at`, `updated_at`) values (10999, ?, 10999, 1000, paid, wallet, repurchase_payment, 2025-09-03 09:47:54, 2025-09-03 09:47:54))  
6716:[2025-09-03 18:54:50] local.ERROR: There are no commands defined in the "filament" namespace. {"exception":"[object] (Symfony\\Component\\Console\\Exception\\NamespaceNotFoundException(code: 0): There are no commands defined in the \"filament\" namespace. at D:\\xampp\\htdocs\\sellvada\\vendor\\symfony\\console\\Application.php:659)
6726:[2025-09-03 18:54:54] local.ERROR: Command "make:filament-user" is not defined.
6811:[2025-09-03 19:09:03] local.ERROR: SQLSTATE[HY000]: General error: 1364 Field 'referral_id' doesn't have a default value (Connection: mysql, SQL: insert into `users` (`name`, `email`, `password`, `updated_at`, `created_at`) values (admin, yogesh@gmail.com, $2y$12$WwLT/uaF1fU1JMZvHFCntuqXuUG4lC0kZibgTQ226/6y9a7OIKDfy, 2025-09-03 19:09:02, 2025-09-03 19:09:02)) {"exception":"[object] (Illuminate\\Database\\QueryException(code: HY000): SQLSTATE[HY000]: General error: 1364 Field 'referral_id' doesn't have a default value (Connection: mysql, SQL: insert into `users` (`name`, `email`, `password`, `updated_at`, `created_at`) values (admin, yogesh@gmail.com, $2y$12$WwLT/uaF1fU1JMZvHFCntuqXuUG4lC0kZibgTQ226/6y9a7OIKDfy, 2025-09-03 19:09:02, 2025-09-03 19:09:02)) at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php:824)
6842:[previous exception] [object] (PDOException(code: HY000): SQLSTATE[HY000]: General error: 1364 Field 'referral_id' doesn't have a default value at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\MySqlConnection.php:53)
6875:[2025-09-03 19:11:46] local.ERROR: SQLSTATE[HY000]: General error: 1364 Field 'referral_id' doesn't have a default value (Connection: mysql, SQL: insert into `users` (`name`, `email`, `password`, `updated_at`, `created_at`) values (admin, yogesh@gmail.com, $2y$12$t5.RyWKcxdl0VxrClEv1BeALIwjoNVTaBrNUePZHy1PCRCR6j/mF., 2025-09-03 19:11:46, 2025-09-03 19:11:46)) {"exception":"[object] (Illuminate\\Database\\QueryException(code: HY000): SQLSTATE[HY000]: General error: 1364 Field 'referral_id' doesn't have a default value (Connection: mysql, SQL: insert into `users` (`name`, `email`, `password`, `updated_at`, `created_at`) values (admin, yogesh@gmail.com, $2y$12$t5.RyWKcxdl0VxrClEv1BeALIwjoNVTaBrNUePZHy1PCRCR6j/mF., 2025-09-03 19:11:46, 2025-09-03 19:11:46)) at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php:824)
6906:[previous exception] [object] (PDOException(code: HY000): SQLSTATE[HY000]: General error: 1364 Field 'referral_id' doesn't have a default value at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\MySqlConnection.php:53)
6939:[2025-09-03 19:17:50] local.ERROR: Type of App\Filament\Pages\Dashboard::$navigationIcon must be BackedEnum|string|null (as in class Filament\Pages\Page) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Type of App\\Filament\\Pages\\Dashboard::$navigationIcon must be BackedEnum|string|null (as in class Filament\\Pages\\Page) at D:\\xampp\\htdocs\\sellvada\\app\\Filament\\Pages\\Dashboard.php:7)
6943:[2025-09-03 19:19:07] local.ERROR: Type of App\Filament\Pages\Dashboard::$navigationIcon must be BackedEnum|string|null (as in class Filament\Pages\Page) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Type of App\\Filament\\Pages\\Dashboard::$navigationIcon must be BackedEnum|string|null (as in class Filament\\Pages\\Page) at D:\\xampp\\htdocs\\sellvada\\app\\Filament\\Pages\\Dashboard.php:7)
6947:[2025-09-04 05:59:05] local.ERROR: Array to string conversion (Connection: mysql, SQL: insert into `sell` (`buyer_id`, `sponsor_id`, `income_to_user_id`, `leg`, `product`, `amount`, `income`, `income_type`, `level`, `order_no`, `status`, `type`, `details`, `created_at`, `updated_at`) values (10999, 10982, 10982, L, Super Food (Silver), 3000, 0, DIRECT, ?, ORD-MFV6L4BA, paid, silver, ?, 2025-09-04 05:59:04, 2025-09-04 05:59:04)) {"userId":10999,"exception":"[object] (Illuminate\\Database\\QueryException(code: 0): Array to string conversion (Connection: mysql, SQL: insert into `sell` (`buyer_id`, `sponsor_id`, `income_to_user_id`, `leg`, `product`, `amount`, `income`, `income_type`, `level`, `order_no`, `status`, `type`, `details`, `created_at`, `updated_at`) values (10999, 10982, 10982, L, Super Food (Silver), 3000, 0, DIRECT, ?, ORD-MFV6L4BA, paid, silver, ?, 2025-09-04 05:59:04, 2025-09-04 05:59:04)) at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php:824)
6971:#22 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
6972:#23 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
7015:[previous exception] [object] (ErrorException(code: 0): Array to string conversion at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php:718)
7017:#0 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(258): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Array to string...', 'D:\\\\xampp\\\\htdocs...', 718)
7044:#27 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
7045:#28 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
7088:[2025-09-04 06:19:20] local.ERROR: Array to string conversion (Connection: mysql, SQL: insert into `sell` (`buyer_id`, `sponsor_id`, `income_to_user_id`, `leg`, `product`, `amount`, `income`, `income_type`, `level`, `order_no`, `status`, `type`, `details`, `created_at`, `updated_at`) values (10999, 10982, 10982, L, Super Food (Silver), 3000, 0, DIRECT, ?, ORD-IMO4UAMM, paid, silver, ?, 2025-09-04 06:19:20, 2025-09-04 06:19:20)) {"userId":10999,"exception":"[object] (Illuminate\\Database\\QueryException(code: 0): Array to string conversion (Connection: mysql, SQL: insert into `sell` (`buyer_id`, `sponsor_id`, `income_to_user_id`, `leg`, `product`, `amount`, `income`, `income_type`, `level`, `order_no`, `status`, `type`, `details`, `created_at`, `updated_at`) values (10999, 10982, 10982, L, Super Food (Silver), 3000, 0, DIRECT, ?, ORD-IMO4UAMM, paid, silver, ?, 2025-09-04 06:19:20, 2025-09-04 06:19:20)) at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php:824)
7112:#22 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
7113:#23 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
7156:[previous exception] [object] (ErrorException(code: 0): Array to string conversion at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php:718)
7158:#0 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(258): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Array to string...', 'D:\\\\xampp\\\\htdocs...', 718)
7185:#27 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
7186:#28 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
7229:[2025-09-04 06:21:15] local.ERROR: Array to string conversion (Connection: mysql, SQL: insert into `sell` (`buyer_id`, `sponsor_id`, `income_to_user_id`, `leg`, `product`, `amount`, `income`, `income_type`, `level`, `order_no`, `status`, `type`, `details`, `created_at`, `updated_at`) values (10999, 10982, 10982, L, Super Food (Silver), 3000, 0, DIRECT, ?, ORD-FGJXE20P, paid, silver, ?, 2025-09-04 06:21:15, 2025-09-04 06:21:15)) {"userId":10999,"exception":"[object] (Illuminate\\Database\\QueryException(code: 0): Array to string conversion (Connection: mysql, SQL: insert into `sell` (`buyer_id`, `sponsor_id`, `income_to_user_id`, `leg`, `product`, `amount`, `income`, `income_type`, `level`, `order_no`, `status`, `type`, `details`, `created_at`, `updated_at`) values (10999, 10982, 10982, L, Super Food (Silver), 3000, 0, DIRECT, ?, ORD-FGJXE20P, paid, silver, ?, 2025-09-04 06:21:15, 2025-09-04 06:21:15)) at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php:824)
7253:#22 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
7254:#23 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
7297:[previous exception] [object] (ErrorException(code: 0): Array to string conversion at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php:718)
7299:#0 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(258): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Array to string...', 'D:\\\\xampp\\\\htdocs...', 718)
7326:#27 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
7327:#28 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
7370:[2025-09-04 10:43:47] local.ERROR: syntax error, unexpected variable "$exists" {"exception":"[object] (ParseError(code: 0): syntax error, unexpected variable \"$exists\" at D:\\xampp\\htdocs\\sellvada\\app\\Console\\Commands\\RunBinaryMatching.php:210)
7382:[2025-09-04 10:45:00] local.ERROR: Illuminate\Database\Query\Builder::update(): Argument #1 ($values) must be of type array, string given, called in D:\xampp\htdocs\sellvada\app\Console\Commands\RunBinaryMatching.php on line 257 {"exception":"[object] (TypeError(code: 0): Illuminate\\Database\\Query\\Builder::update(): Argument #1 ($values) must be of type array, string given, called in D:\\xampp\\htdocs\\sellvada\\app\\Console\\Commands\\RunBinaryMatching.php on line 257 at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Query\\Builder.php:3897)
7401:[2025-09-04 18:34:49] local.ERROR: Target class [admin] does not exist. {"userId":11031,"exception":"[object] (Illuminate\\Contracts\\Container\\BindingResolutionException(code: 0): Target class [admin] does not exist. at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php:1162)
7420:#17 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
7421:#18 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
7484:#18 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
7485:#19 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
7528:[2025-09-04 18:34:56] local.ERROR: Target class [admin] does not exist. {"userId":11031,"exception":"[object] (Illuminate\\Contracts\\Container\\BindingResolutionException(code: 0): Target class [admin] does not exist. at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php:1162)
7555:[2025-09-04 18:36:08] local.ERROR: syntax error, unexpected token "->" {"exception":"[object] (ParseError(code: 0): syntax error, unexpected token \"->\" at D:\\xampp\\htdocs\\sellvada\\app\\Providers\\Filament\\AdminPanelProvider.php:59)
7570:[2025-09-04 18:37:06] local.ERROR: Route [admin.users.index] not defined. {"exception":"[object] (Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Route [admin.users.index] not defined. at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\UrlGenerator.php:526)
7613:[2025-09-04 18:37:34] local.ERROR: Route [admin.users.index] not defined. {"exception":"[object] (Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Route [admin.users.index] not defined. at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\UrlGenerator.php:526)
7656:[2025-09-04 18:37:37] local.ERROR: Route [admin.users.index] not defined. {"exception":"[object] (Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Route [admin.users.index] not defined. at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\UrlGenerator.php:526)
7699:[2025-09-04 18:37:39] local.ERROR: Route [admin.users.index] not defined. {"exception":"[object] (Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Route [admin.users.index] not defined. at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\UrlGenerator.php:526)
7742:[2025-09-04 18:38:28] local.ERROR: Route [admin.users.index] not defined. {"exception":"[object] (Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Route [admin.users.index] not defined. at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\UrlGenerator.php:526)
7783:[2025-09-04 18:38:35] local.ERROR: Route [admin.users.index] not defined. {"exception":"[object] (Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Route [admin.users.index] not defined. at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\UrlGenerator.php:526)
7824:[2025-09-04 18:42:25] local.ERROR: Route [admin.users.index] not defined. {"exception":"[object] (Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Route [admin.users.index] not defined. at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\UrlGenerator.php:526)
7865:[2025-09-04 18:42:26] local.ERROR: Route [admin.users.index] not defined. {"exception":"[object] (Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Route [admin.users.index] not defined. at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\UrlGenerator.php:526)
7906:[2025-09-04 18:46:14] local.ERROR: Target class [admin] does not exist. {"userId":11031,"exception":"[object] (Illuminate\\Contracts\\Container\\BindingResolutionException(code: 0): Target class [admin] does not exist. at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php:1162)
7925:#17 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
7926:#18 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
7989:#18 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
7990:#19 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
8033:[2025-09-04 18:46:20] local.ERROR: Target class [admin] does not exist. {"userId":11031,"exception":"[object] (Illuminate\\Contracts\\Container\\BindingResolutionException(code: 0): Target class [admin] does not exist. at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php:1162)
8060:[2025-09-04 18:46:53] local.ERROR: Target class [admin] does not exist. {"userId":11031,"exception":"[object] (Illuminate\\Contracts\\Container\\BindingResolutionException(code: 0): Target class [admin] does not exist. at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php:1162)
8079:#17 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
8080:#18 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
8143:#18 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
8144:#19 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
8187:[2025-09-04 18:46:54] local.ERROR: Target class [admin] does not exist. {"userId":11031,"exception":"[object] (Illuminate\\Contracts\\Container\\BindingResolutionException(code: 0): Target class [admin] does not exist. at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php:1162)
8214:[2025-09-04 18:48:40] local.ERROR: Target class [admin] does not exist. {"userId":11031,"exception":"[object] (Illuminate\\Contracts\\Container\\BindingResolutionException(code: 0): Target class [admin] does not exist. at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php:1162)
8233:#17 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
8234:#18 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
8297:#18 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
8298:#19 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
8341:[2025-09-04 18:48:42] local.ERROR: Target class [admin] does not exist. {"userId":11031,"exception":"[object] (Illuminate\\Contracts\\Container\\BindingResolutionException(code: 0): Target class [admin] does not exist. at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php:1162)
8368:[2025-09-04 18:51:16] local.ERROR: Target class [admin] does not exist. {"userId":11031,"exception":"[object] (Illuminate\\Contracts\\Container\\BindingResolutionException(code: 0): Target class [admin] does not exist. at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php:1162)
8387:#17 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
8388:#18 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
8451:#18 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
8452:#19 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(219): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
8495:[2025-09-04 18:51:18] local.ERROR: Target class [admin] does not exist. {"userId":11031,"exception":"[object] (Illuminate\\Contracts\\Container\\BindingResolutionException(code: 0): Target class [admin] does not exist. at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php:1162)
8522:[2025-09-04 18:53:39] local.ERROR: Cannot redeclare App\Providers\AppServiceProvider::boot() {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot redeclare App\\Providers\\AppServiceProvider::boot() at D:\\xampp\\htdocs\\sellvada\\app\\Providers\\AppServiceProvider.php:28)
8526:[2025-09-05 05:14:56] local.ERROR: SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it (Connection: mysql, SQL: select * from `sessions` where `id` = KXjLds4K3OEk4FwjfnZ92I5Z4m2lRr2urez3nK0E limit 1) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 2002): SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it (Connection: mysql, SQL: select * from `sessions` where `id` = KXjLds4K3OEk4FwjfnZ92I5Z4m2lRr2urez3nK0E limit 1) at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php:824)
8658:[2025-09-05 05:15:23] local.ERROR: SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it (Connection: mysql, SQL: select * from `sessions` where `id` = KXjLds4K3OEk4FwjfnZ92I5Z4m2lRr2urez3nK0E limit 1) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 2002): SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it (Connection: mysql, SQL: select * from `sessions` where `id` = KXjLds4K3OEk4FwjfnZ92I5Z4m2lRr2urez3nK0E limit 1) at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php:824)
8790:[2025-09-06 05:18:58] local.ERROR: Class "Filament\PanelProvider" not found {"exception":"[object] (Error(code: 0): Class \"Filament\\PanelProvider\" not found at D:\\xampp\\htdocs\\sellvada\\app\\Providers\\Filament\\AdminPanelProvider.php:24)
8804:[2025-09-06 05:20:23] local.ERROR: Class "Filament\PanelProvider" not found {"exception":"[object] (Error(code: 0): Class \"Filament\\PanelProvider\" not found at D:\\xampp\\htdocs\\sellvada\\app\\Providers\\Filament\\AdminPanelProvider.php:24)
8818:[2025-09-06 05:20:35] local.ERROR: Class "Filament\PanelProvider" not found {"exception":"[object] (Error(code: 0): Class \"Filament\\PanelProvider\" not found at D:\\xampp\\htdocs\\sellvada\\app\\Providers\\Filament\\AdminPanelProvider.php:24)
8832:[2025-09-06 05:20:35] local.ERROR: Class "Filament\PanelProvider" not found {"exception":"[object] (Error(code: 0): Class \"Filament\\PanelProvider\" not found at D:\\xampp\\htdocs\\sellvada\\app\\Providers\\Filament\\AdminPanelProvider.php:24)
8846:[2025-09-06 05:20:36] local.ERROR: Class "Filament\PanelProvider" not found {"exception":"[object] (Error(code: 0): Class \"Filament\\PanelProvider\" not found at D:\\xampp\\htdocs\\sellvada\\app\\Providers\\Filament\\AdminPanelProvider.php:24)
8860:[2025-09-06 05:25:30] local.ERROR: Namespace declaration statement has to be the very first statement or after any declare call in the script {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Namespace declaration statement has to be the very first statement or after any declare call in the script at D:\\xampp\\htdocs\\sellvada\\app\\Providers\\Filament\\AdminPanelProvider.php:3)
8864:[2025-09-06 05:25:31] local.ERROR: Namespace declaration statement has to be the very first statement or after any declare call in the script {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Namespace declaration statement has to be the very first statement or after any declare call in the script at D:\\xampp\\htdocs\\sellvada\\app\\Providers\\Filament\\AdminPanelProvider.php:3)
8868:[2025-09-06 05:25:31] local.ERROR: Namespace declaration statement has to be the very first statement or after any declare call in the script {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Namespace declaration statement has to be the very first statement or after any declare call in the script at D:\\xampp\\htdocs\\sellvada\\app\\Providers\\Filament\\AdminPanelProvider.php:3)
8872:[2025-09-06 05:25:32] local.ERROR: Namespace declaration statement has to be the very first statement or after any declare call in the script {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Namespace declaration statement has to be the very first statement or after any declare call in the script at D:\\xampp\\htdocs\\sellvada\\app\\Providers\\Filament\\AdminPanelProvider.php:3)
8876:[2025-09-06 05:25:32] local.ERROR: Namespace declaration statement has to be the very first statement or after any declare call in the script {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Namespace declaration statement has to be the very first statement or after any declare call in the script at D:\\xampp\\htdocs\\sellvada\\app\\Providers\\Filament\\AdminPanelProvider.php:3)
8880:[2025-09-06 05:25:33] local.ERROR: Namespace declaration statement has to be the very first statement or after any declare call in the script {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Namespace declaration statement has to be the very first statement or after any declare call in the script at D:\\xampp\\htdocs\\sellvada\\app\\Providers\\Filament\\AdminPanelProvider.php:3)
8884:[2025-09-06 05:27:43] local.ERROR: Class "BladeUI\Heroicons\BladeHeroiconsServiceProvider" not found {"exception":"[object] (Error(code: 0): Class \"BladeUI\\Heroicons\\BladeHeroiconsServiceProvider\" not found at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php:960)
8897:[2025-09-06 05:27:44] local.ERROR: Class "BladeUI\Heroicons\BladeHeroiconsServiceProvider" not found {"exception":"[object] (Error(code: 0): Class \"BladeUI\\Heroicons\\BladeHeroiconsServiceProvider\" not found at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php:960)
8910:[2025-09-06 05:27:44] local.ERROR: Class "BladeUI\Heroicons\BladeHeroiconsServiceProvider" not found {"exception":"[object] (Error(code: 0): Class \"BladeUI\\Heroicons\\BladeHeroiconsServiceProvider\" not found at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php:960)
8923:[2025-09-06 05:27:45] local.ERROR: Class "BladeUI\Heroicons\BladeHeroiconsServiceProvider" not found {"exception":"[object] (Error(code: 0): Class \"BladeUI\\Heroicons\\BladeHeroiconsServiceProvider\" not found at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php:960)
8936:[2025-09-06 05:27:46] local.ERROR: Class "BladeUI\Heroicons\BladeHeroiconsServiceProvider" not found {"exception":"[object] (Error(code: 0): Class \"BladeUI\\Heroicons\\BladeHeroiconsServiceProvider\" not found at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php:960)
8949:[2025-09-06 05:27:46] local.ERROR: Class "BladeUI\Heroicons\BladeHeroiconsServiceProvider" not found {"exception":"[object] (Error(code: 0): Class \"BladeUI\\Heroicons\\BladeHeroiconsServiceProvider\" not found at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php:960)
8962:[2025-09-06 05:32:09] local.ERROR: include(D:\xampp\htdocs\sellvada\vendor\composer/../../app/Providers/Filament/AdminPanelProvider.php): Failed to open stream: No such file or directory {"exception":"[object] (ErrorException(code: 0): include(D:\\xampp\\htdocs\\sellvada\\vendor\\composer/../../app/Providers/Filament/AdminPanelProvider.php): Failed to open stream: No such file or directory at D:\\xampp\\htdocs\\sellvada\\vendor\\composer\\ClassLoader.php:576)
8964:#0 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(258): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'include(D:\\\\xamp...', 'D:\\\\xampp\\\\htdocs...', 576)
8978:[2025-09-06 05:35:17] local.ERROR: Class "BladeUI\Heroicons\BladeHeroiconsServiceProvider" not found {"exception":"[object] (Error(code: 0): Class \"BladeUI\\Heroicons\\BladeHeroiconsServiceProvider\" not found at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\ProviderRepository.php:205)
8991:[2025-09-06 05:35:17] local.ERROR: Class "BladeUI\Heroicons\BladeHeroiconsServiceProvider" not found {"exception":"[object] (Error(code: 0): Class \"BladeUI\\Heroicons\\BladeHeroiconsServiceProvider\" not found at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\ProviderRepository.php:205)
9004:[2025-09-06 05:35:18] local.ERROR: Class "BladeUI\Heroicons\BladeHeroiconsServiceProvider" not found {"exception":"[object] (Error(code: 0): Class \"BladeUI\\Heroicons\\BladeHeroiconsServiceProvider\" not found at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\ProviderRepository.php:205)
9017:[2025-09-06 05:35:18] local.ERROR: Class "BladeUI\Heroicons\BladeHeroiconsServiceProvider" not found {"exception":"[object] (Error(code: 0): Class \"BladeUI\\Heroicons\\BladeHeroiconsServiceProvider\" not found at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\ProviderRepository.php:205)
9030:[2025-09-06 05:35:19] local.ERROR: Class "BladeUI\Heroicons\BladeHeroiconsServiceProvider" not found {"exception":"[object] (Error(code: 0): Class \"BladeUI\\Heroicons\\BladeHeroiconsServiceProvider\" not found at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\ProviderRepository.php:205)
9043:[2025-09-06 05:39:20] local.ERROR: foreach() argument must be of type array|object, int given {"exception":"[object] (ErrorException(code: 0): foreach() argument must be of type array|object, int given at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\RegisterProviders.php:51)
9045:#0 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(258): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'foreach() argum...', 'D:\\\\xampp\\\\htdocs...', 51)
9055:[2025-09-06 05:39:21] local.ERROR: foreach() argument must be of type array|object, int given {"exception":"[object] (ErrorException(code: 0): foreach() argument must be of type array|object, int given at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\RegisterProviders.php:51)
9057:#0 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(258): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'foreach() argum...', 'D:\\\\xampp\\\\htdocs...', 51)
9067:[2025-09-06 05:39:21] local.ERROR: foreach() argument must be of type array|object, int given {"exception":"[object] (ErrorException(code: 0): foreach() argument must be of type array|object, int given at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\RegisterProviders.php:51)
9069:#0 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(258): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'foreach() argum...', 'D:\\\\xampp\\\\htdocs...', 51)
9079:[2025-09-06 05:39:22] local.ERROR: foreach() argument must be of type array|object, int given {"exception":"[object] (ErrorException(code: 0): foreach() argument must be of type array|object, int given at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\RegisterProviders.php:51)
9081:#0 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(258): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'foreach() argum...', 'D:\\\\xampp\\\\htdocs...', 51)
9091:[2025-09-06 05:39:22] local.ERROR: foreach() argument must be of type array|object, int given {"exception":"[object] (ErrorException(code: 0): foreach() argument must be of type array|object, int given at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\RegisterProviders.php:51)
9093:#0 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(258): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'foreach() argum...', 'D:\\\\xampp\\\\htdocs...', 51)
9103:[2025-09-06 05:39:23] local.ERROR: foreach() argument must be of type array|object, int given {"exception":"[object] (ErrorException(code: 0): foreach() argument must be of type array|object, int given at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\RegisterProviders.php:51)
9105:#0 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(258): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'foreach() argum...', 'D:\\\\xampp\\\\htdocs...', 51)
9120:#3 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(403): Illuminate\\Log\\LogManager->error('array_merge(): ...', Array)
9121:#4 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(366): Illuminate\\Foundation\\Exceptions\\Handler->reportThrowable(Object(TypeError))
9122:#5 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(620): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(TypeError))
9123:#6 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(199): Illuminate\\Foundation\\Console\\Kernel->reportException(Object(TypeError))
9128:[2025-09-06 07:40:39] laravel.ERROR: array_merge(): Argument #2 must be of type array, int given {"exception":"[object] (TypeError(code: 0): array_merge(): Argument #2 must be of type array, int given at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php:102)
9145:#3 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(403): Illuminate\\Log\\LogManager->error('array_merge(): ...', Array)
9146:#4 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(366): Illuminate\\Foundation\\Exceptions\\Handler->reportThrowable(Object(TypeError))
9147:#5 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(620): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(TypeError))
9148:#6 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(199): Illuminate\\Foundation\\Console\\Kernel->reportException(Object(TypeError))
9153:[2025-09-06 07:40:40] laravel.ERROR: array_merge(): Argument #2 must be of type array, int given {"exception":"[object] (TypeError(code: 0): array_merge(): Argument #2 must be of type array, int given at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php:102)
9170:#3 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(403): Illuminate\\Log\\LogManager->error('array_merge(): ...', Array)
9171:#4 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(366): Illuminate\\Foundation\\Exceptions\\Handler->reportThrowable(Object(TypeError))
9172:#5 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(620): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(TypeError))
9173:#6 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(199): Illuminate\\Foundation\\Console\\Kernel->reportException(Object(TypeError))
9178:[2025-09-06 07:40:40] laravel.ERROR: array_merge(): Argument #2 must be of type array, int given {"exception":"[object] (TypeError(code: 0): array_merge(): Argument #2 must be of type array, int given at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php:102)
9195:#3 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(403): Illuminate\\Log\\LogManager->error('array_merge(): ...', Array)
9196:#4 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(366): Illuminate\\Foundation\\Exceptions\\Handler->reportThrowable(Object(TypeError))
9197:#5 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(620): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(TypeError))
9198:#6 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(199): Illuminate\\Foundation\\Console\\Kernel->reportException(Object(TypeError))
9203:[2025-09-06 07:40:41] laravel.ERROR: array_merge(): Argument #2 must be of type array, int given {"exception":"[object] (TypeError(code: 0): array_merge(): Argument #2 must be of type array, int given at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php:102)
9220:#3 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(403): Illuminate\\Log\\LogManager->error('array_merge(): ...', Array)
9221:#4 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(366): Illuminate\\Foundation\\Exceptions\\Handler->reportThrowable(Object(TypeError))
9222:#5 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(620): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(TypeError))
9223:#6 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(199): Illuminate\\Foundation\\Console\\Kernel->reportException(Object(TypeError))
9228:[2025-09-06 07:40:41] laravel.ERROR: array_merge(): Argument #2 must be of type array, int given {"exception":"[object] (TypeError(code: 0): array_merge(): Argument #2 must be of type array, int given at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php:102)
9245:#3 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(403): Illuminate\\Log\\LogManager->error('array_merge(): ...', Array)
9246:#4 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(366): Illuminate\\Foundation\\Exceptions\\Handler->reportThrowable(Object(TypeError))
9247:#5 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(620): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(TypeError))
9248:#6 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(199): Illuminate\\Foundation\\Console\\Kernel->reportException(Object(TypeError))
9253:[2025-09-06 07:40:42] laravel.ERROR: array_merge(): Argument #2 must be of type array, int given {"exception":"[object] (TypeError(code: 0): array_merge(): Argument #2 must be of type array, int given at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\LoadConfiguration.php:102)
9265:[2025-09-06 05:42:06] local.ERROR: foreach() argument must be of type array|object, int given {"exception":"[object] (ErrorException(code: 0): foreach() argument must be of type array|object, int given at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\RegisterProviders.php:51)
9267:#0 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(258): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'foreach() argum...', 'D:\\\\xampp\\\\htdocs...', 51)
9277:[2025-09-06 05:42:07] local.ERROR: foreach() argument must be of type array|object, int given {"exception":"[object] (ErrorException(code: 0): foreach() argument must be of type array|object, int given at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\RegisterProviders.php:51)
9279:#0 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(258): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'foreach() argum...', 'D:\\\\xampp\\\\htdocs...', 51)
9289:[2025-09-06 05:42:07] local.ERROR: foreach() argument must be of type array|object, int given {"exception":"[object] (ErrorException(code: 0): foreach() argument must be of type array|object, int given at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\RegisterProviders.php:51)
9291:#0 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(258): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'foreach() argum...', 'D:\\\\xampp\\\\htdocs...', 51)
9301:[2025-09-06 05:42:08] local.ERROR: foreach() argument must be of type array|object, int given {"exception":"[object] (ErrorException(code: 0): foreach() argument must be of type array|object, int given at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\RegisterProviders.php:51)
9303:#0 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(258): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'foreach() argum...', 'D:\\\\xampp\\\\htdocs...', 51)
9313:[2025-09-06 05:42:08] local.ERROR: foreach() argument must be of type array|object, int given {"exception":"[object] (ErrorException(code: 0): foreach() argument must be of type array|object, int given at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\RegisterProviders.php:51)
9315:#0 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(258): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'foreach() argum...', 'D:\\\\xampp\\\\htdocs...', 51)
9325:[2025-09-06 05:42:08] local.ERROR: foreach() argument must be of type array|object, int given {"exception":"[object] (ErrorException(code: 0): foreach() argument must be of type array|object, int given at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\RegisterProviders.php:51)
9327:#0 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(258): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'foreach() argum...', 'D:\\\\xampp\\\\htdocs...', 51)
9337:[2025-09-06 05:43:01] local.ERROR: foreach() argument must be of type array|object, int given {"exception":"[object] (ErrorException(code: 0): foreach() argument must be of type array|object, int given at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\RegisterProviders.php:51)
9339:#0 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(258): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'foreach() argum...', 'D:\\\\xampp\\\\htdocs...', 51)
9349:[2025-09-06 05:43:02] local.ERROR: foreach() argument must be of type array|object, int given {"exception":"[object] (ErrorException(code: 0): foreach() argument must be of type array|object, int given at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\RegisterProviders.php:51)
9351:#0 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(258): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'foreach() argum...', 'D:\\\\xampp\\\\htdocs...', 51)
9361:[2025-09-06 05:43:03] local.ERROR: foreach() argument must be of type array|object, int given {"exception":"[object] (ErrorException(code: 0): foreach() argument must be of type array|object, int given at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\RegisterProviders.php:51)
9363:#0 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(258): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'foreach() argum...', 'D:\\\\xampp\\\\htdocs...', 51)
9373:[2025-09-06 05:43:03] local.ERROR: foreach() argument must be of type array|object, int given {"exception":"[object] (ErrorException(code: 0): foreach() argument must be of type array|object, int given at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\RegisterProviders.php:51)
9375:#0 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(258): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'foreach() argum...', 'D:\\\\xampp\\\\htdocs...', 51)
9385:[2025-09-06 05:43:04] local.ERROR: foreach() argument must be of type array|object, int given {"exception":"[object] (ErrorException(code: 0): foreach() argument must be of type array|object, int given at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\RegisterProviders.php:51)
9387:#0 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(258): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'foreach() argum...', 'D:\\\\xampp\\\\htdocs...', 51)
9397:[2025-09-06 05:43:04] local.ERROR: foreach() argument must be of type array|object, int given {"exception":"[object] (ErrorException(code: 0): foreach() argument must be of type array|object, int given at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\RegisterProviders.php:51)
9399:#0 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(258): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'foreach() argum...', 'D:\\\\xampp\\\\htdocs...', 51)
9409:[2025-09-06 05:44:51] local.ERROR: foreach() argument must be of type array|object, int given {"exception":"[object] (ErrorException(code: 0): foreach() argument must be of type array|object, int given at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\RegisterProviders.php:51)
9411:#0 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(258): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'foreach() argum...', 'D:\\\\xampp\\\\htdocs...', 51)
9421:[2025-09-06 05:44:52] local.ERROR: foreach() argument must be of type array|object, int given {"exception":"[object] (ErrorException(code: 0): foreach() argument must be of type array|object, int given at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\RegisterProviders.php:51)
9423:#0 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(258): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'foreach() argum...', 'D:\\\\xampp\\\\htdocs...', 51)
9433:[2025-09-06 05:44:52] local.ERROR: foreach() argument must be of type array|object, int given {"exception":"[object] (ErrorException(code: 0): foreach() argument must be of type array|object, int given at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\RegisterProviders.php:51)
9435:#0 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(258): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'foreach() argum...', 'D:\\\\xampp\\\\htdocs...', 51)
9445:[2025-09-06 05:44:53] local.ERROR: foreach() argument must be of type array|object, int given {"exception":"[object] (ErrorException(code: 0): foreach() argument must be of type array|object, int given at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\RegisterProviders.php:51)
9447:#0 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(258): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'foreach() argum...', 'D:\\\\xampp\\\\htdocs...', 51)
9457:[2025-09-06 05:44:53] local.ERROR: foreach() argument must be of type array|object, int given {"exception":"[object] (ErrorException(code: 0): foreach() argument must be of type array|object, int given at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\RegisterProviders.php:51)
9459:#0 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(258): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'foreach() argum...', 'D:\\\\xampp\\\\htdocs...', 51)
9469:[2025-09-06 05:44:54] local.ERROR: foreach() argument must be of type array|object, int given {"exception":"[object] (ErrorException(code: 0): foreach() argument must be of type array|object, int given at D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\RegisterProviders.php:51)
9471:#0 D:\\xampp\\htdocs\\sellvada\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(258): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'foreach() argum...', 'D:\\\\xampp\\\\htdocs...', 51)
